version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: factory-db
    restart: always
    ports:
      - "5432:5432"   #default PostgreSQL port 
    env_file:
      - .env  #fallback environment variables file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: factory-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env      
    environment:
      PORT: ${PORT}
      LOG_LEVEL: ${LOG_LEVEL}
      LOG_ENABLED: ${LOG_ENABLED}
      LOGGER_NAME: ${LOGGER_NAME}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
    depends_on:
      - db

volumes:
  db-data:
