version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: factory-db
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}   #default PostgreSQL port 
    env_file:
      - .env  #fallback environment variables file
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: factory-api
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env      
    depends_on:
      - db

volumes:
  db-data:
