ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB
ARG POSTGRES_HOST

FROM postgres:latest

RUN apt-get update \
    && apt-get install -y postgresql-contrib \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./init-scripts/ /docker-entrypoint-initdb.d/

RUN echo "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" > /docker-entrypoint-initdb.d/1-create-user.sql \
    && echo "CREATE DATABASE $POSTGRES_DB WITH OWNER $POSTGRES_USER;" > /docker-entrypoint-initdb.d/2-create-db.sql \
    && echo "GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;" > /docker-entrypoint-initdb.d/3-grant-privileges.sql \
    && echo "CREATE EXTENSION IF NOT EXISTS \"pgcrypto\";" > /docker-entrypoint-initdb.d/4-pgcrypto.sql

ENV POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    POSTGRES_HOST=$POSTGRES_HOST

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
